# Generated by Django 5.1.3 on 2024-12-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер преподавательской')),
            ],
            options={
                'verbose_name': 'преподавательская',
                'verbose_name_plural': 'преподавательские',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя преподавателя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Изображение')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('full_time', models.BooleanField(default=True, help_text='Уберите галочку, если преподаватель работает не на полную ставку', verbose_name='Работает на полную ставку')),
                ('additional_work', models.TextField(blank=True, null=True, verbose_name='Дополнительная работа')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.audience', verbose_name='Аудитория')),
                ('courses', models.ManyToManyField(related_name='teachers', to='department.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
    ]
